-- Create and populate our inventory using a single insert with many rows
CREATE TABLE inventory
(
    id          NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 201) NOT NULL PRIMARY KEY,
    item_name   VARCHAR2(255) NOT NULL,
    details     VARCHAR2(512),
    price       FLOAT
);
GRANT SELECT ON inventory to c##dbzuser;
ALTER TABLE inventory
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO inventory VALUES (NULL, 'laptop', '15-inch laptop with 8GB RAM', 799.99);
INSERT INTO inventory VALUES (NULL, 'smartphone', '6.5-inch smartphone with 128GB storage', 699.99);
INSERT INTO inventory VALUES (NULL, 'headphones', 'Wireless noise-canceling headphones', 249.99);
INSERT INTO inventory VALUES (NULL, 'tablet', '10-inch tablet with 64GB storage', 399.99);
INSERT INTO inventory VALUES (NULL, 'smartwatch', 'Fitness tracking smartwatch', 199.99);

-- Create and populate the stock levels using multiple inserts
CREATE TABLE stock_levels
(
    item_id  NUMBER(4) NOT NULL PRIMARY KEY,
    quantity NUMBER(4) NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory (id)
);
GRANT SELECT ON stock_levels to c##dbzuser;
ALTER TABLE stock_levels
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO stock_levels VALUES (201, 50);
INSERT INTO stock_levels VALUES (202, 100);
INSERT INTO stock_levels VALUES (203, 75);
INSERT INTO stock_levels VALUES (204, 30);
INSERT INTO stock_levels VALUES (205, 60);

-- Create some users ...
CREATE TABLE users
(
    id         NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 2001) NOT NULL PRIMARY KEY,
    username   VARCHAR2(255) NOT NULL,
    email      VARCHAR2(255) NOT NULL UNIQUE,
    created_at DATE NOT NULL
);
GRANT SELECT ON users to c##dbzuser;
ALTER TABLE users
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO users VALUES (NULL, 'johndoe', 'john.doe@example.com', '01-MAR-2024');
INSERT INTO users VALUES (NULL, 'janedoe', 'jane.doe@example.com', '02-MAR-2024');
INSERT INTO users VALUES (NULL, 'bobsmith', 'bob.smith@example.com', '03-MAR-2024');

-- Create some purchases
CREATE TABLE purchases
(
    id           NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 20001) NOT NULL PRIMARY KEY,
    purchase_date DATE NOT NULL,
    user_id       NUMBER(4) NOT NULL,
    quantity      NUMBER(4) NOT NULL,
    item_id       NUMBER(4) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (item_id) REFERENCES inventory (id)
);
GRANT SELECT ON purchases to c##dbzuser;
ALTER TABLE purchases
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO purchases VALUES (NULL, '05-MAR-2024', 2001, 1, 201);
INSERT INTO purchases VALUES (NULL, '06-MAR-2024', 2002, 2, 203);
INSERT INTO purchases VALUES (NULL, '07-MAR-2024', 2003, 1, 202);